// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { defineConfig } from "prisma/config";

/**
 * Adapter the Prisma migrate CLI uses. Order of precedence:
 *   1. TURSO_DATABASE_URL (+ TURSO_AUTH_TOKEN) — split form
 *   2. DATABASE_URL when it starts with libsql: — combined form (Turso)
 *   3. local SQLite fallback prisma/dev.db
 *
 * Prisma's url-parser is strict about scheme, so when we're using libsql we
 * still pass it a placeholder file: URL via the datasource block — the real
 * connection happens through the adapter.
 */
function buildAdapter() {
  const tursoUrl = process.env["TURSO_DATABASE_URL"];
  const tursoToken = process.env["TURSO_AUTH_TOKEN"];
  if (tursoUrl) {
    return new PrismaLibSql({ url: tursoUrl, authToken: tursoToken });
  }
  const databaseUrl = process.env["DATABASE_URL"] ?? "";
  if (databaseUrl.startsWith("libsql:")) {
    return new PrismaLibSql({ url: databaseUrl });
  }
  return new PrismaLibSql({
    url: databaseUrl || `file:${process.cwd()}/prisma/dev.db`,
  });
}

const datasourceUrl = (() => {
  const url = process.env["DATABASE_URL"] ?? "";
  // Prisma's parser only accepts file: for sqlite. When the real URL is
  // libsql, give the parser a harmless local placeholder — the adapter
  // does the real connection.
  if (url.startsWith("libsql:") || process.env["TURSO_DATABASE_URL"]) {
    return `file:${process.cwd()}/prisma/.placeholder.db`;
  }
  return url || `file:${process.cwd()}/prisma/dev.db`;
})();

export default defineConfig({
  schema: "prisma/schema.prisma",
  datasource: { url: datasourceUrl },
  migrations: {
    path: "prisma/migrations",
    adapter: async () => buildAdapter(),
  },
});
